# -*- coding: utf-8 -*-
"""Translating Different Languages.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_1gM-Yv6he7VBIyx01lcdMGaqopAgzT5

# Goslate Library
"""

!pip install goslate

import goslate
inserted_text = "Python is so Powerful"
new_gs = goslate.Goslate()
new_gs.translate(inserted_text, 'es')

"""# Translate Library"""

!pip install translate

#Translate text to another language
from translate import Translator
translator= Translator(from_lang="english", to_lang="german")
translation = translator.translate("This is a useful library!")
print(translation)

#Translate Document or text file
from translate import Translator

file = open('projects.txt', 'r')
new_content = file.read()
translating_file = Translator(to_lang = "german")
result = translator.translate(new_content)
print(result)

"""# TextBlob Library"""

!pip install textblob

from textblob import TextBlob
adding_blob = TextBlob('Easy way to translate a text in python')
adding_blob.translate(to = 'fr')

