# -*- coding: utf-8 -*-
"""Store Employee Details using Class.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lgOjvZKzMIXaEHCSPR-U8qxSyLtqJnvM
"""

class Employee:
    count = 0
    def __init__(self, name, position, salary):
        self.name=name
        self.position=position
        self.salary=salary
        Employee.count+=1
    def displayCount(self):
        print("There are %d employees" % Employee.count)
    def displayDetails(self):
        print("Name:", self.name, ", Position:", self.position, ", Salary:", self.salary)
        
emp1 = Employee("Alpha", "HR", 30000)
emp2 = Employee("Bakarr", "Manager", 90000)
emp3 = Employee("Messi", "Programmer", 50000)
emp4 = Employee("Salah", "Engineer",65000)

emp4.displayCount() #Count of employees

print("**Information about Employee**")
emp1.displayDetails()
emp2.displayDetails()
emp3.displayDetails()
emp4.displayDetails()

